/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SubFrames;
import Application_Gui.EquipmentFrame;

/**
 *
 * @author mount
 */
public class Add_Equipment extends javax.swing.JFrame {
    
        /**
     * Creates new form Add_Equipment
     */
    public Add_Equipment() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Equipment_Name_TextField = new javax.swing.JTextField();
        Quantity_Available_TextField = new javax.swing.JTextField();
        Add_Equipment_Btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Equipment Name:");

        jLabel2.setText("Number:");

        Add_Equipment_Btn.setText("Add Equipment");
        Add_Equipment_Btn.addActionListener(this::Add_Equipment_BtnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Equipment_Name_TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(Quantity_Available_TextField))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(131, Short.MAX_VALUE)
                .addComponent(Add_Equipment_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Equipment_Name_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Quantity_Available_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(Add_Equipment_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Add_Equipment_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_Equipment_BtnActionPerformed
                                                          
        
        String name = Equipment_Name_TextField.getText().trim().toLowerCase();
        String qtyStr = Quantity_Available_TextField.getText();

        
        if (name.isEmpty() || qtyStr.isEmpty()) {
            System.out.println("Validation Error: Please fill all fields.");
            return;
        }

        
        int qty = Integer.parseInt(qtyStr);
        int id = Application_Gui.EquipmentFrame.Equipment_List.size() + 1;

        boolean duplicateExists = EquipmentFrame.Equipment_List.stream()
            .anyMatch(s -> s.name.equalsIgnoreCase(name)); 

        if (duplicateExists) {
            javax.swing.JOptionPane.showMessageDialog(this, "A equpment with this name already registered.", "Duplicate Found", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Classes.Equipment eq = new Classes.Equipment(id, name, qty);

       
        Application_Gui.EquipmentFrame.Equipment_List.add(eq);
        Application_Gui.EquipmentFrame.loadEquipmentToList();

        
        System.out.println("System: Equipment " + name + " injected successfully.");
        javax.swing.JOptionPane.showMessageDialog(this, "Equipment " + name + " added successfully!", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);

        
        this.dispose();
    
    }//GEN-LAST:event_Add_Equipment_BtnActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_Equipment_Btn;
    private javax.swing.JTextField Equipment_Name_TextField;
    private javax.swing.JTextField Quantity_Available_TextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
