/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SubFrames;

import Application_Gui.OrganizerFrame;

/**
 *
 * @author mount
 */
public class Add_Organizer extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Add_Organizer.class.getName());

    /**
     * Creates new form Add_Organizer
     */
    public Add_Organizer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Organizer_Name_TextField = new javax.swing.JTextField();
        Organizer_Email_TextField = new javax.swing.JTextField();
        Club_Name_TextField = new javax.swing.JTextField();
        Organizer_Name = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Add_Organizer_Btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Club_Name_TextField.addActionListener(this::Club_Name_TextFieldActionPerformed);

        Organizer_Name.setText("Organizer Name:");

        jLabel2.setText("Organizer_Email:");

        jLabel3.setText("Club_Name:");

        Add_Organizer_Btn.setText("Add Organizer");
        Add_Organizer_Btn.addActionListener(this::Add_Organizer_BtnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Organizer_Email_TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(Club_Name_TextField)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(Organizer_Name)
                        .addGap(44, 44, 44)
                        .addComponent(Organizer_Name_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(Add_Organizer_Btn)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Organizer_Name)
                    .addComponent(Organizer_Name_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Organizer_Email_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Club_Name_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(Add_Organizer_Btn)
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Club_Name_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Club_Name_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Club_Name_TextFieldActionPerformed

    private void Add_Organizer_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_Organizer_BtnActionPerformed
        String name = Organizer_Name_TextField.getText();
        String email = Organizer_Email_TextField.getText();
        String club = Club_Name_TextField.getText();

        if (name.isEmpty() || email.isEmpty() || club.isEmpty()) return;

        int id = OrganizerFrame.Organizer_List.size() + 1;
        Classes.Organizer o = new Classes.Organizer(id, name, email, club);

        OrganizerFrame.Organizer_List.add(o);
        OrganizerFrame.loadOrganizersToTable();
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_Add_Organizer_BtnActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_Organizer_Btn;
    private javax.swing.JTextField Club_Name_TextField;
    private javax.swing.JTextField Organizer_Email_TextField;
    private javax.swing.JLabel Organizer_Name;
    private javax.swing.JTextField Organizer_Name_TextField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
