/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SubFrames;

import Application_Gui.StudentFrame;

/**
 *
 * @author mount
 */
public class Add_Student extends javax.swing.JFrame {
    
   
    /**
     * Creates new form Add_Student
     */
    public Add_Student() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Student_Name_TextField = new javax.swing.JTextField();
        Student_Email_TextField = new javax.swing.JTextField();
        Student_Level_TextField = new javax.swing.JTextField();
        Student_Departement_TextField = new javax.swing.JTextField();
        Submit_Student_Btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Name:");

        jLabel2.setText("Email:");

        jLabel3.setText("Level:");

        jLabel4.setText("Department:");

        Student_Departement_TextField.addActionListener(this::Student_Departement_TextFieldActionPerformed);

        Submit_Student_Btn.setText("Add Student");
        Submit_Student_Btn.addActionListener(this::Submit_Student_BtnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(58, 58, 58))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Student_Name_TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                            .addComponent(Student_Email_TextField)
                            .addComponent(Student_Level_TextField)
                            .addComponent(Student_Departement_TextField))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(Submit_Student_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(129, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Student_Name_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Student_Email_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Student_Level_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Student_Departement_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(Submit_Student_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Submit_Student_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submit_Student_BtnActionPerformed
        String name = Student_Name_TextField.getText().trim().toLowerCase();
        String email = Student_Email_TextField.getText().trim();

        
        String emailRegex = "^(?=.{1,254}$)(?=.{1,64}@)[A-Za-z0-9!#$%&'*+/=?^_`{|}~-]+"
                          + "(?:\\.[A-Za-z0-9!#$%&'*+/=?^_`{|}~-]+)*@"
                          + "(?:[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?\\.)+"
                          + "[A-Za-z]{2,}$";

        if (!email.matches(emailRegex)) {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Invalid email format. Try again.",
                "Validation Error",
                javax.swing.JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        String level = Student_Level_TextField.getText();
        String department = Student_Departement_TextField.getText();
        
        if (name.isEmpty() || email.isEmpty() || level.isEmpty() || department.isEmpty()) {
            System.out.println("Validation Error: Please fill all fields.");
            return;
        }
        
        int id = StudentFrame.Students_List.size() + 1;
        
        boolean duplicateEmail = StudentFrame.Students_List.stream()
            .anyMatch(s -> s.email.equalsIgnoreCase(email));
        boolean duplicateName = StudentFrame.Students_List.stream()
            .anyMatch(s -> s.name.equalsIgnoreCase(name));

        if (duplicateEmail) {
            javax.swing.JOptionPane.showMessageDialog(this, "A student with this email is already registered.", "Duplicate Found", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (duplicateName) {
            javax.swing.JOptionPane.showMessageDialog(this, "A student with this name is already registered.", "Duplicate Found", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Classes.Student s = new Classes.Student(id, name, email, level, department);

        
        StudentFrame.Students_List.add(s);

        
        StudentFrame.loadStudentsToTable();
        System.out.println("System: Student " + name + " injected successfully.");

        
        javax.swing.JOptionPane.showMessageDialog(this, "Student " + name + " added successfully!", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);

        this.dispose();
    }//GEN-LAST:event_Submit_Student_BtnActionPerformed

    private void Student_Departement_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Student_Departement_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Student_Departement_TextFieldActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Student_Departement_TextField;
    private javax.swing.JTextField Student_Email_TextField;
    private javax.swing.JTextField Student_Level_TextField;
    private javax.swing.JTextField Student_Name_TextField;
    private javax.swing.JButton Submit_Student_Btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
