/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SubFrames;

import Application_Gui.RoomFrame;

/**
 *
 * @author mount
 */
public class Add_Room extends javax.swing.JFrame {
    
   
    /**
     * Creates new form Add_Room
     */
    public Add_Room() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jjjj = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Room_Number_TextField = new javax.swing.JTextField();
        Building_TextField = new javax.swing.JTextField();
        Capacity_TextField = new javax.swing.JTextField();
        Add_Room_Btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jjjj.setText("Room Number:");

        jLabel2.setText("Building:");

        jLabel3.setText("Capacity:");

        Room_Number_TextField.addActionListener(this::Room_Number_TextFieldActionPerformed);

        Add_Room_Btn.setText("Add Room");
        Add_Room_Btn.addActionListener(this::Add_Room_BtnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(85, 85, 85)
                        .addComponent(Capacity_TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jjjj)
                            .addComponent(jLabel2))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Room_Number_TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(Building_TextField))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(134, Short.MAX_VALUE)
                .addComponent(Add_Room_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Room_Number_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jjjj))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Building_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Capacity_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(Add_Room_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Add_Room_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_Room_BtnActionPerformed
                                            
       
        String roomNum = Room_Number_TextField.getText().trim();
        String building = Building_TextField.getText().trim();
        String capacityStr = Capacity_TextField.getText().trim();

        
        if (roomNum.isEmpty() || building.isEmpty() || capacityStr.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "All fields are strictly required.", "Validation Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        
        int capacity;
        try {
            capacity = Integer.parseInt(capacityStr);
            if (capacity <= 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Capacity must be greater than zero.", "Logic Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Capacity must be a valid integer.", "Type Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        
        boolean duplicateExists = RoomFrame.Room_List.stream()
            .anyMatch(r -> r.roomNumber.equalsIgnoreCase(roomNum) && r.building.equalsIgnoreCase(building));

        if (duplicateExists) {
            javax.swing.JOptionPane.showMessageDialog(this, "Room " + roomNum + " already exists in " + building + ".", "Duplicate Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        
        Classes.Room r = new Classes.Room(roomNum, building, capacity);
        RoomFrame.Room_List.add(r);
        RoomFrame.loadRoomsToTable();

        System.out.println("System: Room " + roomNum + " securely registered in " + building + ".");
        javax.swing.JOptionPane.showMessageDialog(this, "Room " + roomNum + " added successfully!", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        this.dispose(); 

    }//GEN-LAST:event_Add_Room_BtnActionPerformed

    private void Room_Number_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Room_Number_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Room_Number_TextFieldActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_Room_Btn;
    private javax.swing.JTextField Building_TextField;
    private javax.swing.JTextField Capacity_TextField;
    private javax.swing.JTextField Room_Number_TextField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jjjj;
    // End of variables declaration//GEN-END:variables
}
