/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SubFrames;

import Application_Gui.EventFrame;
import Application_Gui.OrganizerFrame;
import Application_Gui.RoomFrame;

/**
 *
 * @author mount
 */
public class Schedule_Event extends javax.swing.JFrame {
    
    /**
     * Creates new form Schedule_Event
     */
    public Schedule_Event() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Event_Code_TextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Start_Hour_TextField = new javax.swing.JTextField();
        Event_Title_TextField = new javax.swing.JTextField();
        Event_Date_TextField = new javax.swing.JTextField();
        End_Hour_TextField = new javax.swing.JTextField();
        Max_Participants_Spinner = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        Select_Room_ComboBox = new javax.swing.JComboBox<>();
        Select_Organizer_ComboBox = new javax.swing.JComboBox<>();
        Schedule_Event_Btn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Event Code:");

        jLabel2.setText("Event Title:");

        jLabel3.setText("Event Date:");

        jLabel4.setText("Start Hour:");

        jLabel5.setText("End Hour: ");

        jLabel6.setText("Max Participants:");

        Select_Room_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Select_Organizer_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Schedule_Event_Btn.setText("Schedule Event");
        Schedule_Event_Btn.addActionListener(this::Schedule_Event_BtnActionPerformed);

        jLabel7.setText("Select Room:");

        jLabel8.setText("Select Organizer:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(174, 174, 174))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Start_Hour_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Event_Date_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Event_Title_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Event_Code_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(End_Hour_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Max_Participants_Spinner)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(Select_Organizer_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(Select_Room_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE)))))))))
                .addGap(66, 66, 66))
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(Schedule_Event_Btn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Event_Code_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Event_Title_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Event_Date_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Start_Hour_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(End_Hour_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(Max_Participants_Spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(Select_Room_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Select_Organizer_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(Schedule_Event_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Schedule_Event_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Schedule_Event_BtnActionPerformed

        
        String code = Event_Code_TextField.getText().trim();
        String title = Event_Title_TextField.getText().trim();
        String date = Event_Date_TextField.getText().trim();
        String startStr = Start_Hour_TextField.getText().trim();
        String endStr = End_Hour_TextField.getText().trim();
        
        
        if (code.isEmpty() || title.isEmpty() || date.isEmpty() || startStr.isEmpty() || endStr.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "All fields are strictly required.", "Validation Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        
        int startHour, endHour;
        try {
            startHour = Integer.parseInt(startStr);
            endHour = Integer.parseInt(endStr);
            
            if (startHour >= endHour) {
                javax.swing.JOptionPane.showMessageDialog(this, "Start hour must be strictly before end hour.", "Logic Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Hours must be valid integers.", "Type Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int maxParticipants = (Integer) Max_Participants_Spinner.getValue();
        if (maxParticipants <= 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Event must have at least 1 participant capacity.", "Logic Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int roomIndex = Select_Room_ComboBox.getSelectedIndex();
        int orgIndex = Select_Organizer_ComboBox.getSelectedIndex();

        if (roomIndex < 0 || orgIndex < 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "You must select both a valid Room and Organizer.", "Validation Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        Classes.Room selectedRoom = RoomFrame.Room_List.get(roomIndex);
        Classes.Organizer selectedOrganizer = OrganizerFrame.Organizer_List.get(orgIndex);
        
        
        if (maxParticipants > selectedRoom.capacity) {
            javax.swing.JOptionPane.showMessageDialog(this, "Room capacity (" + selectedRoom.capacity + ") is too small for " + maxParticipants + " participants.", "Constraint Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

       
        boolean duplicateCode = EventFrame.Event_List.stream().anyMatch(s -> s.code.equalsIgnoreCase(code));
        if (duplicateCode) {
            javax.swing.JOptionPane.showMessageDialog(this, "An event with this code is already registered.", "Duplicate Found", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        boolean duplicateTitle = EventFrame.Event_List.stream().anyMatch(s -> s.title.equalsIgnoreCase(title));
        if (duplicateTitle) {
            javax.swing.JOptionPane.showMessageDialog(this, "An event with this title is already registered.", "Duplicate Found", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        
        Classes.Event newEvent = new Classes.Event(code, title, date, startHour, endHour, maxParticipants);
        newEvent.assignRoom(selectedRoom);
        
        
        for (Classes.Event existingEvent : EventFrame.Event_List) {
            if (existingEvent.room != null && 
                existingEvent.room.roomNumber.equalsIgnoreCase(selectedRoom.roomNumber) && 
                existingEvent.room.building.equalsIgnoreCase(selectedRoom.building)) {
                
                if (newEvent.hasConflict(existingEvent)) {
                    javax.swing.JOptionPane.showMessageDialog(this, 
                        "Scheduling Conflict: Room " + selectedRoom.roomNumber + " is already booked for '" + existingEvent.title + "' during this timeframe.", 
                        "Time Collision", 
                        javax.swing.JOptionPane.ERROR_MESSAGE);
                    return; 
                }
            }
        }

        
        selectedOrganizer.createEvent(newEvent); 
        EventFrame.Event_List.add(newEvent);
        EventFrame.loadEventsToTable();
        
        System.out.println("System: Event '" + title + "' successfully scheduled without conflicts.");
        javax.swing.JOptionPane.showMessageDialog(this, "Event '" + title + "' Scheduled successfully!", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
    }//GEN-LAST:event_Schedule_Event_BtnActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField End_Hour_TextField;
    private javax.swing.JTextField Event_Code_TextField;
    private javax.swing.JTextField Event_Date_TextField;
    private javax.swing.JTextField Event_Title_TextField;
    private javax.swing.JSpinner Max_Participants_Spinner;
    private javax.swing.JButton Schedule_Event_Btn;
    public static javax.swing.JComboBox<String> Select_Organizer_ComboBox;
    public static javax.swing.JComboBox<String> Select_Room_ComboBox;
    private javax.swing.JTextField Start_Hour_TextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
