/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Application_Gui;

import static Application_Gui.RoomFrame.Room_Display_Table;
import static Application_Gui.RoomFrame.Room_List;
import static Application_Gui.RoomFrame.loadRoomsToTable;

/**
 *
 * @author mount
 */
public class EventFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EventFrame.class.getName());

    public static java.util.ArrayList<Classes.Event> Event_List = new java.util.ArrayList<>();
    /**
     * Creates new form EventFrame
     */
    public EventFrame() {
        initComponents();
    }

    public static void loadEventsToTable() {
    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) Event_Display_Table.getModel();
    model.setRowCount(0);
    for (Classes.Event e : Event_List) {
        Object[] row = {
            e.code,
            e.title,
            e.date,
            e.startHour + ":00 - " + e.endHour + ":00",
            e.maxParticipants
        };
        model.addRow(row);
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Event_Display_Table = new javax.swing.JTable();
        Schedule_New_Event_Btn = new javax.swing.JButton();
        Delete_Event_Btn = new javax.swing.JButton();
        Search_Event_TextField = new javax.swing.JTextField();
        Search_Event_Btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Event_Display_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Event_Display_Table);

        Schedule_New_Event_Btn.setText("Schedule new Event ");
        Schedule_New_Event_Btn.addActionListener(this::Schedule_New_Event_BtnActionPerformed);

        Delete_Event_Btn.setText("Delete_Selected");
        Delete_Event_Btn.addActionListener(this::Delete_Event_BtnActionPerformed);

        Search_Event_Btn.setText("Search");
        Search_Event_Btn.addActionListener(this::Search_Event_BtnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Schedule_New_Event_Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Delete_Event_Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(Search_Event_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Search_Event_Btn))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Search_Event_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Search_Event_Btn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(36, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(Schedule_New_Event_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Delete_Event_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Schedule_New_Event_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Schedule_New_Event_BtnActionPerformed

        
        SubFrames.Schedule_Event subFrame = new SubFrames.Schedule_Event();
        
        
        SubFrames.Schedule_Event.Select_Room_ComboBox.removeAllItems();
        SubFrames.Schedule_Event.Select_Organizer_ComboBox.removeAllItems();
        
        
        for (Classes.Room r : RoomFrame.Room_List) {
            SubFrames.Schedule_Event.Select_Room_ComboBox.addItem(r.roomNumber + " (" + r.capacity + " seats)");
        }
        
        
        for (Classes.Organizer o : OrganizerFrame.Organizer_List) {
            SubFrames.Schedule_Event.Select_Organizer_ComboBox.addItem(o.name + " - " + o.clubName);
        }
        
        
        subFrame.setVisible(true);
     // TODO add your handling code here:
    }//GEN-LAST:event_Schedule_New_Event_BtnActionPerformed

    private void Delete_Event_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_Event_BtnActionPerformed
            int selectedRow=Event_Display_Table.getSelectedRow();
            if (selectedRow == -1) {
                System.out.println("System Error: No room selected.");
                return;
            }
            Event_List.remove(selectedRow);
            loadEventsToTable();
    }//GEN-LAST:event_Delete_Event_BtnActionPerformed

    private void Search_Event_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_Event_BtnActionPerformed
        String keyword=Search_Event_TextField.getText().toLowerCase().trim();
           
        if (keyword.isEmpty()) {
            loadEventsToTable();
            return;
        }
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) Event_Display_Table.getModel();
        model.setRowCount(0); 
        
        
        for (Classes.Event e : Event_List) {
            if (e.title.contains(keyword) || e.code.contains(keyword)|| e.date.contains(keyword)) {
                Object[] row = { e.code, e.title, e.date,e.startHour,e.endHour,e.maxParticipants };
                model.addRow(row);
            }
        }
        System.out.println("System: Search executed for '" + keyword + "'");    
    }//GEN-LAST:event_Search_Event_BtnActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete_Event_Btn;
    public static javax.swing.JTable Event_Display_Table;
    private javax.swing.JButton Schedule_New_Event_Btn;
    private javax.swing.JButton Search_Event_Btn;
    private javax.swing.JTextField Search_Event_TextField;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
