/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Application_Gui;

/**
 *
 * @author mount
 */
public class MainMenuFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainMenuFrame.class.getName());

    /**
     * Creates new form MainMenuFrame
     */
    public MainMenuFrame() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }
    private StudentFrame studentFrameInstance = null;
    private EventFrame eventFrameInstance = null;
    private OrganizerFrame organizerFrameInstance = null;
    private RoomFrame roomFrameInsatance = null;
    private EquipmentFrame equipmentFrameInsatance = null;
    private RegistrationFrame registrationFrameInsatance = null;
    private ReportFrame reportFrameInstance = null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Manage_Students_Btn = new javax.swing.JButton();
        Manage_Organizers_Btn = new javax.swing.JButton();
        Manage_Room_Btn = new javax.swing.JButton();
        Manage_Equipment_Btn = new javax.swing.JButton();
        Manage_Events_Btn = new javax.swing.JButton();
        Register_Events_Btn = new javax.swing.JButton();
        View_Reports_Btn = new javax.swing.JButton();
        Exit_Btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Campus Event Registration System.");

        Manage_Students_Btn.setText("Manage Students");
        Manage_Students_Btn.addActionListener(this::Manage_Students_BtnActionPerformed);

        Manage_Organizers_Btn.setText("Manage Organizers");
        Manage_Organizers_Btn.addActionListener(this::Manage_Organizers_BtnActionPerformed);

        Manage_Room_Btn.setText("Manage Room");
        Manage_Room_Btn.addActionListener(this::Manage_Room_BtnActionPerformed);

        Manage_Equipment_Btn.setText("Manage Equipment");
        Manage_Equipment_Btn.addActionListener(this::Manage_Equipment_BtnActionPerformed);

        Manage_Events_Btn.setText("Manage Events");
        Manage_Events_Btn.addActionListener(this::Manage_Events_BtnActionPerformed);

        Register_Events_Btn.setText("Register for Events");
        Register_Events_Btn.addActionListener(this::Register_Events_BtnActionPerformed);

        View_Reports_Btn.setText("View Reports");
        View_Reports_Btn.addActionListener(this::View_Reports_BtnActionPerformed);

        Exit_Btn.setText("Exit");
        Exit_Btn.addActionListener(this::Exit_BtnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(View_Reports_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(Exit_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Manage_Equipment_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Manage_Events_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Manage_Students_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Manage_Organizers_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Manage_Room_Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Register_Events_Btn, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))))
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Manage_Students_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Manage_Organizers_Btn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Manage_Room_Btn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Manage_Equipment_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Manage_Events_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Register_Events_Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(View_Reports_Btn, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(Exit_Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Manage_Students_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Manage_Students_BtnActionPerformed
        if (studentFrameInstance == null || !studentFrameInstance.isDisplayable()) {
        studentFrameInstance = new StudentFrame();
        }
        studentFrameInstance.setVisible(true);
        studentFrameInstance.toFront();       
    }//GEN-LAST:event_Manage_Students_BtnActionPerformed

    private void Manage_Organizers_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Manage_Organizers_BtnActionPerformed
        if(organizerFrameInstance == null || !organizerFrameInstance.isDisplayable()){
            organizerFrameInstance = new OrganizerFrame();
        } 
        new OrganizerFrame().setVisible(true);
        organizerFrameInstance.toFront();
    }//GEN-LAST:event_Manage_Organizers_BtnActionPerformed

    private void Manage_Room_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Manage_Room_BtnActionPerformed
        if(roomFrameInsatance == null || !roomFrameInsatance.isDisplayable()){
            roomFrameInsatance = new RoomFrame();
        }
        new RoomFrame().setVisible(true); 
        roomFrameInsatance.toFront();
    }//GEN-LAST:event_Manage_Room_BtnActionPerformed

    private void Manage_Equipment_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Manage_Equipment_BtnActionPerformed
        if(equipmentFrameInsatance == null || !equipmentFrameInsatance.isDisplayable()){
            equipmentFrameInsatance = new EquipmentFrame();
        }
        new EquipmentFrame().setVisible(true); 
        equipmentFrameInsatance.toFront();       
    }//GEN-LAST:event_Manage_Equipment_BtnActionPerformed

    private void Manage_Events_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Manage_Events_BtnActionPerformed
        if(eventFrameInstance == null || !eventFrameInstance.isDisplayable()){
            eventFrameInstance = new EventFrame();
        }
        new EventFrame().setVisible(true); 
        eventFrameInstance.toFront();       
    }//GEN-LAST:event_Manage_Events_BtnActionPerformed

    private void Register_Events_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Register_Events_BtnActionPerformed
        
        if(registrationFrameInsatance == null || !registrationFrameInsatance.isDisplayable()){
            registrationFrameInsatance = new RegistrationFrame();
        }
        
      
        Application_Gui.RegistrationFrame.Select_Student_ComboBox.removeAllItems();
        Application_Gui.RegistrationFrame.Select_Event_ComboBox.removeAllItems();
        
        
        for (Classes.Student s : Application_Gui.StudentFrame.Students_List) {
            Application_Gui.RegistrationFrame.Select_Student_ComboBox.addItem(s.name + " (" + s.email + ")");
        }
        
        
        for (Classes.Event e : Application_Gui.EventFrame.Event_List) {
            Application_Gui.RegistrationFrame.Select_Event_ComboBox.addItem(e.code + " - " + e.title);
        }
        
        
        new RegistrationFrame().setVisible(true);
        registrationFrameInsatance.toFront();
    }//GEN-LAST:event_Register_Events_BtnActionPerformed

    private void View_Reports_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_View_Reports_BtnActionPerformed

        if(reportFrameInstance == null || !reportFrameInstance.isDisplayable()){
            reportFrameInstance = new ReportFrame();
        }
        new ReportFrame().setVisible(true); 
        Application_Gui.ReportFrame.loadReportsToTable();
        reportFrameInstance.toFront();
    }//GEN-LAST:event_View_Reports_BtnActionPerformed

    private void Exit_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit_BtnActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_Exit_BtnActionPerformed


        /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form with IPC Singleton Lock */
        java.awt.EventQueue.invokeLater(() -> {
            MainMenuFrame mainApp = new MainMenuFrame();
            
            final int IPC_PORT = 13337; 
            
            try {
                // Attempt to claim the port lock
                java.net.ServerSocket serverSocket = new java.net.ServerSocket(IPC_PORT, 1, java.net.InetAddress.getLocalHost());
                
                // Lock acquired. We are the Alpha instance.
                // Spawn a daemon thread to listen for clones trying to start.
                Thread listenerThread = new Thread(() -> {
                    while (true) {
                        try (java.net.Socket socket = serverSocket.accept()) {
                            // A clone just pinged us. Bring our UI to the front.
                            java.awt.EventQueue.invokeLater(() -> {
                                // If minimized, restore it
                                mainApp.setExtendedState(javax.swing.JFrame.NORMAL);
                                // Force focus
                                mainApp.toFront();
                                mainApp.repaint();
                            });
                        } catch (java.io.IOException e) {
                            break;
                        }
                    }
                });
                listenerThread.setDaemon(true); // Ensures this thread doesn't prevent application shutdown
                listenerThread.start();
                
                // Safe to display the UI
                mainApp.setVisible(true);

            } catch (java.net.BindException e) {
                // Port is already occupied. We are a clone.
                System.out.println("System: Application is already running. Pinging the master process...");
                
                try (java.net.Socket pingSocket = new java.net.Socket(java.net.InetAddress.getLocalHost(), IPC_PORT)) {
                    // Just establishing the connection sends the signal.
                } catch (Exception ex) {
                    // Ignore network hiccups on exit
                } 
                
                // Terminate this duplicate instance immediately
                System.exit(0);
                
            } catch (Exception e) {
                // Fallback safety net in case of severe network adapter issues
                mainApp.setVisible(true);
            }
        });
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit_Btn;
    private javax.swing.JButton Manage_Equipment_Btn;
    private javax.swing.JButton Manage_Events_Btn;
    private javax.swing.JButton Manage_Organizers_Btn;
    private javax.swing.JButton Manage_Room_Btn;
    private javax.swing.JButton Manage_Students_Btn;
    private javax.swing.JButton Register_Events_Btn;
    private javax.swing.JButton View_Reports_Btn;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
