/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Application_Gui;

/**
 *
 * @author mount
 */
public class MainMenuFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainMenuFrame.class.getName());

    /**
     * Creates new form MainMenuFrame
     */
    public MainMenuFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Manage_Students_Btn = new javax.swing.JButton();
        Manage_Organizers_Btn = new javax.swing.JButton();
        Manage_Room_Btn = new javax.swing.JButton();
        Manage_Equipment_Btn = new javax.swing.JButton();
        Manage_Events_Btn = new javax.swing.JButton();
        Register_Events_Btn = new javax.swing.JButton();
        View_Reports_Btn = new javax.swing.JButton();
        Exit_Btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Campus Event Registration System.");

        Manage_Students_Btn.setText("Manage Students");
        Manage_Students_Btn.addActionListener(this::Manage_Students_BtnActionPerformed);

        Manage_Organizers_Btn.setText("Manage Organizers");
        Manage_Organizers_Btn.addActionListener(this::Manage_Organizers_BtnActionPerformed);

        Manage_Room_Btn.setText("Manage Room");
        Manage_Room_Btn.addActionListener(this::Manage_Room_BtnActionPerformed);

        Manage_Equipment_Btn.setText("Manage Equipment");
        Manage_Equipment_Btn.addActionListener(this::Manage_Equipment_BtnActionPerformed);

        Manage_Events_Btn.setText("Manage Events");
        Manage_Events_Btn.addActionListener(this::Manage_Events_BtnActionPerformed);

        Register_Events_Btn.setText("Register for Events");
        Register_Events_Btn.addActionListener(this::Register_Events_BtnActionPerformed);

        View_Reports_Btn.setText("View Reports");
        View_Reports_Btn.addActionListener(this::View_Reports_BtnActionPerformed);

        Exit_Btn.setText("Exit");
        Exit_Btn.addActionListener(this::Exit_BtnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Manage_Equipment_Btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Manage_Events_Btn)
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Manage_Students_Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(47, 47, 47)
                        .addComponent(Manage_Organizers_Btn)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(Manage_Room_Btn)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Register_Events_Btn)
                        .addGap(16, 16, 16))))
            .addGroup(layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(View_Reports_Btn)
                .addGap(87, 87, 87)
                .addComponent(Exit_Btn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(155, 155, 155))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Manage_Students_Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Manage_Organizers_Btn)
                    .addComponent(Manage_Room_Btn))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Manage_Equipment_Btn)
                    .addComponent(Manage_Events_Btn)
                    .addComponent(Register_Events_Btn))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(View_Reports_Btn)
                    .addComponent(Exit_Btn))
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Manage_Students_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Manage_Students_BtnActionPerformed
        new StudentFrame().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_Manage_Students_BtnActionPerformed

    private void Manage_Organizers_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Manage_Organizers_BtnActionPerformed
         new OrganizerFrame().setVisible(true);
    }//GEN-LAST:event_Manage_Organizers_BtnActionPerformed

    private void Manage_Room_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Manage_Room_BtnActionPerformed
        new RoomFrame().setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_Manage_Room_BtnActionPerformed

    private void Manage_Equipment_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Manage_Equipment_BtnActionPerformed
        new EquipmentFrame().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_Manage_Equipment_BtnActionPerformed

    private void Manage_Events_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Manage_Events_BtnActionPerformed
        new EventFrame().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_Manage_Events_BtnActionPerformed

    private void Register_Events_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Register_Events_BtnActionPerformed
        
        
        Application_Gui.RegistrationFrame regFrame = new Application_Gui.RegistrationFrame();
        
        
        Application_Gui.RegistrationFrame.Select_Student_ComboBox.removeAllItems();
        Application_Gui.RegistrationFrame.Select_Event_ComboBox.removeAllItems();
        
        
        for (Classes.Student s : Application_Gui.StudentFrame.Students_List) {
            Application_Gui.RegistrationFrame.Select_Student_ComboBox.addItem(s.name + " (" + s.email + ")");
        }
        
        
        for (Classes.Event e : Application_Gui.EventFrame.Event_List) {
            Application_Gui.RegistrationFrame.Select_Event_ComboBox.addItem(e.code + " - " + e.title);
        }
        
        
        regFrame.setVisible(true);
          // TODO add your handling code here:
    }//GEN-LAST:event_Register_Events_BtnActionPerformed

    private void View_Reports_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_View_Reports_BtnActionPerformed

        Application_Gui.ReportFrame rFrame = new Application_Gui.ReportFrame();
        
       
        Application_Gui.ReportFrame.loadReportsToTable();
        
        rFrame.setVisible(true);
    
    }//GEN-LAST:event_View_Reports_BtnActionPerformed

    private void Exit_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit_BtnActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_Exit_BtnActionPerformed


        /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainMenuFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit_Btn;
    private javax.swing.JButton Manage_Equipment_Btn;
    private javax.swing.JButton Manage_Events_Btn;
    private javax.swing.JButton Manage_Organizers_Btn;
    private javax.swing.JButton Manage_Room_Btn;
    private javax.swing.JButton Manage_Students_Btn;
    private javax.swing.JButton Register_Events_Btn;
    private javax.swing.JButton View_Reports_Btn;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
