/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Application_Gui;

import static Application_Gui.RoomFrame.Room_Display_Table;
import static Application_Gui.RoomFrame.Room_List;
import static Application_Gui.RoomFrame.loadRoomsToTable;



public class OrganizerFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(OrganizerFrame.class.getName());

    /**
     * Creates new form OrganizerFrame
     */
    public static java.util.ArrayList<Classes.Organizer> Organizer_List = new java.util.ArrayList<>();
    
    public OrganizerFrame() {
        initComponents();
    }
    
    public static void loadOrganizersToTable() {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) Organizer_Display_Table.getModel();
        model.setRowCount(0);
        for (Classes.Organizer o : Organizer_List) {
            Object[] row = { o.id, o.name, o.email, o.clubName };
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Organizer_Display_Table = new javax.swing.JTable();
        Add_New_Organizer_Btn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Search_Organizer_Btn = new javax.swing.JButton();
        Search_Organizer_TextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Organizer_Display_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Organizer_Display_Table);

        Add_New_Organizer_Btn.setText("Add New Organizer");
        Add_New_Organizer_Btn.addActionListener(this::Add_New_Organizer_BtnActionPerformed);

        jButton1.setText("Deletet Selected");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        Search_Organizer_Btn.setText("Search");
        Search_Organizer_Btn.addActionListener(this::Search_Organizer_BtnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Add_New_Organizer_Btn, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(Search_Organizer_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Search_Organizer_Btn))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Search_Organizer_Btn)
                    .addComponent(Search_Organizer_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(Add_New_Organizer_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Add_New_Organizer_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_New_Organizer_BtnActionPerformed
        new SubFrames.Add_Organizer().setVisible(true);      // TODO add your handling code here:
    }//GEN-LAST:event_Add_New_Organizer_BtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int selectedRow = Organizer_Display_Table.getSelectedRow(); 
        if(selectedRow ==-1){
            System.out.println("System Error: No room selected.");
            return;
        }
        Organizer_List.remove(selectedRow);
        loadOrganizersToTable();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Search_Organizer_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_Organizer_BtnActionPerformed
            String keyword=Search_Organizer_TextField.getText().toLowerCase().trim();
            if (keyword.isEmpty()) {
                loadRoomsToTable();
                return;
            }
            
            javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) Organizer_Display_Table.getModel();
            model.setRowCount(0); 
        
        
            for (Classes.Organizer o : Organizer_List) {
                if (o.name.contains(keyword) || o.email.contains(keyword)|| o.clubName.contains(keyword)) {
                    Object[] row = { o.id, o.name, o.email,o.clubName };
                    model.addRow(row);
                }
            }
            System.out.println("System: Search executed for '" + keyword + "'");
    }//GEN-LAST:event_Search_Organizer_BtnActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_New_Organizer_Btn;
    public static javax.swing.JTable Organizer_Display_Table;
    private javax.swing.JButton Search_Organizer_Btn;
    private javax.swing.JTextField Search_Organizer_TextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
