/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Application_Gui;

/**
 *
 * @author mount
 */
public class RegistrationFrame extends javax.swing.JFrame {
    
    

    public static java.util.ArrayList<Classes.Registration> Registration_List = new java.util.ArrayList<>();
    /**
     * Creates new form RegistrationFrame
     */
    public RegistrationFrame() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Submit_Registration_Btn = new javax.swing.JButton();
        Select_Event_ComboBox = new javax.swing.JComboBox<>();
        Select_Student_ComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Select Student:");

        jLabel2.setText("Select Event:");

        Submit_Registration_Btn.setText("Register");
        Submit_Registration_Btn.addActionListener(this::Submit_Registration_BtnActionPerformed);

        Select_Event_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Select_Student_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Select_Student_ComboBox, 0, 152, Short.MAX_VALUE)
                            .addComponent(Select_Event_ComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(Submit_Registration_Btn)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Select_Student_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Select_Event_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(Submit_Registration_Btn)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Submit_Registration_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submit_Registration_BtnActionPerformed

        int studentIndex = Select_Student_ComboBox.getSelectedIndex();
        int eventIndex = Select_Event_ComboBox.getSelectedIndex();

        
        
        if (studentIndex < 0 || eventIndex < 0) {
            System.out.println("Validation Error: Please select both a student and an event.");
            return;
        }

        
        if (Application_Gui.StudentFrame.Students_List.isEmpty()) {
            System.out.println("System Error: No students exist in the database. Add a student first.");
            return;
        }
        
        if (Application_Gui.EventFrame.Event_List.isEmpty()) {
            System.out.println("System Error: No events exist in the database. Schedule an event first.");
            return;
        }

        
        Classes.Student selectedStudent = Application_Gui.StudentFrame.Students_List.get(studentIndex);
        Classes.Event selectedEvent = Application_Gui.EventFrame.Event_List.get(eventIndex);

        
        int regId = Registration_List.size() + 1;
        String currentDate = "2026-04-06"; 
        Classes.Registration reg = new Classes.Registration(regId, currentDate, "Pending", selectedStudent, selectedEvent);
        
        
        reg.confirmRegistration(); 
        
        
        Registration_List.add(reg);
        
        
        System.out.println("System: Registration sequence completed for " + selectedStudent.name);
        this.dispose();
            // TODO add your handling code here:
    }//GEN-LAST:event_Submit_Registration_BtnActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox<String> Select_Event_ComboBox;
    public static javax.swing.JComboBox<String> Select_Student_ComboBox;
    private javax.swing.JButton Submit_Registration_Btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
