/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Application_Gui;

import static Application_Gui.StudentFrame.Student_Display_Table;
import static Application_Gui.StudentFrame.Students_List;

/**
 *
 * @author mount
 */
public class RoomFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RoomFrame.class.getName());

    public static java.util.ArrayList<Classes.Room> Room_List = new java.util.ArrayList<>();
    /**
     * Creates new form RoomFrame
     */
    public RoomFrame() {
        initComponents();
    }
    
    public static void loadRoomsToTable() {
    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) Room_Display_Table.getModel();
    model.setRowCount(0);
    for (Classes.Room r : Room_List) {
        Object[] row = { r.roomNumber, r.building, r.capacity };
        model.addRow(row);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Room_Display_Table = new javax.swing.JTable();
        Add_New_Room_Btn = new javax.swing.JButton();
        Delete_Room_Btn = new javax.swing.JButton();
        Search_Room_TextField = new javax.swing.JTextField();
        Search_Room_Btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Room_Display_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Room_Display_Table);

        Add_New_Room_Btn.setText("Add New Room");
        Add_New_Room_Btn.addActionListener(this::Add_New_Room_BtnActionPerformed);

        Delete_Room_Btn.setText("Delete Selected");
        Delete_Room_Btn.addActionListener(this::Delete_Room_BtnActionPerformed);

        Search_Room_Btn.setText("Search");
        Search_Room_Btn.addActionListener(this::Search_Room_BtnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Add_New_Room_Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Delete_Room_Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Search_Room_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Search_Room_Btn)
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Search_Room_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Search_Room_Btn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(Add_New_Room_Btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Delete_Room_Btn)
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Add_New_Room_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_New_Room_BtnActionPerformed
        new SubFrames.Add_Room().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_Add_New_Room_BtnActionPerformed

    private void Delete_Room_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_Room_BtnActionPerformed

        int selectedRow = Room_Display_Table.getSelectedRow();
        if (selectedRow == -1) {
            System.out.println("System Error: No room selected.");
            return;
        }
        Room_List.remove(selectedRow); 
        loadRoomsToTable();
    }//GEN-LAST:event_Delete_Room_BtnActionPerformed

    private void Search_Room_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_Room_BtnActionPerformed
           String keyword=Search_Room_TextField.getText().toLowerCase().trim();
           
            if (keyword.isEmpty()) {
                loadRoomsToTable();
                return;
            }
            javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) Room_Display_Table.getModel();
            model.setRowCount(0); 
        
        
            for (Classes.Room r : Room_List) {
                if (r.roomNumber.contains(keyword) || r.building.contains(keyword)) {
                    Object[] row = { r.roomNumber, r.building, r.capacity };
                    model.addRow(row);
                }
            }
            System.out.println("System: Search executed for '" + keyword + "'");
    }//GEN-LAST:event_Search_Room_BtnActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_New_Room_Btn;
    private javax.swing.JButton Delete_Room_Btn;
    public static javax.swing.JTable Room_Display_Table;
    private javax.swing.JButton Search_Room_Btn;
    private javax.swing.JTextField Search_Room_TextField;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
