/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Application_Gui;

/**
 *
 * @author mount
 */

import java.util.ArrayList;
import Classes.Student;
import javax.swing.table.DefaultTableModel;

public class StudentFrame extends javax.swing.JFrame {
    
    
    /**
     * Creates new form StudentFrame
     */
    public static ArrayList<Student> Students_List = new ArrayList<>();
    
    public StudentFrame() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }
    public static void loadStudentsToTable() {
     
        DefaultTableModel model = (DefaultTableModel) Student_Display_Table.getModel();
        
        model.setRowCount(0);
        
        
        for (Student s : Students_List) {
            Object[] row = {
                s.id,
                s.name,
                s.email,
                s.level,
                s.department
            };
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Student_Display_Table = new javax.swing.JTable();
        Add_New_Student_Btn = new javax.swing.JButton();
        Delete_Student_Btn = new javax.swing.JButton();
        Search_Student_Btn = new javax.swing.JButton();
        Search_Student_TextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Student_Display_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Number", "Name", "Email", "Level", "Department"
            }
        ));
        Student_Display_Table.setToolTipText("");
        jScrollPane1.setViewportView(Student_Display_Table);

        Add_New_Student_Btn.setText("Add New Student");
        Add_New_Student_Btn.addActionListener(this::Add_New_Student_BtnActionPerformed);

        Delete_Student_Btn.setText("Delete Selected");
        Delete_Student_Btn.addActionListener(this::Delete_Student_BtnActionPerformed);

        Search_Student_Btn.setText("Search");
        Search_Student_Btn.addActionListener(this::Search_Student_BtnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Add_New_Student_Btn)
                    .addComponent(Delete_Student_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Search_Student_TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Search_Student_Btn)
                        .addGap(42, 42, 42))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Search_Student_Btn)
                    .addComponent(Search_Student_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(41, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Add_New_Student_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(Delete_Student_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Add_New_Student_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_New_Student_BtnActionPerformed
        new SubFrames.Add_Student().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_Add_New_Student_BtnActionPerformed

    private void Delete_Student_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_Student_BtnActionPerformed

        int selectedRow = Student_Display_Table.getSelectedRow();
        
        
        if (selectedRow == -1) {
            System.out.println("System Error: No student selected for deletion.");
            return;
        }
        
        
        Students_List.remove(selectedRow);
        
        // Refresh the display
        loadStudentsToTable();
        System.out.println("System: Student record purged.");
            // TODO add your handling code here:
    }//GEN-LAST:event_Delete_Student_BtnActionPerformed

    private void Search_Student_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_Student_BtnActionPerformed

        String keyword = Search_Student_TextField.getText().toLowerCase().trim();
        
        
        if (keyword.isEmpty()) {
            loadStudentsToTable();
            return;
        }
        
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) Student_Display_Table.getModel();
        model.setRowCount(0); 
        
        
        for (Classes.Student s : Students_List) {
            if (s.name.toLowerCase().contains(keyword) || s.email.toLowerCase().contains(keyword)) {
                Object[] row = { s.id, s.name, s.email, s.level, s.department };
                model.addRow(row);
            }
        }
        System.out.println("System: Search executed for '" + keyword + "'");
            // TODO add your handling code here:
    }//GEN-LAST:event_Search_Student_BtnActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_New_Student_Btn;
    private javax.swing.JButton Delete_Student_Btn;
    private javax.swing.JButton Search_Student_Btn;
    private javax.swing.JTextField Search_Student_TextField;
    public static javax.swing.JTable Student_Display_Table;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
